### ISSUE TITLE
Preventing reminders at midnight

### ISSUE THREAD

**Issue by jfrankl** [dblock/slack-sup2#20]
I'm not sure if this is an issue with how we've configured S'Up, but currently our team receives some reminder messages at midnight. A few people have left our S'Up group because they find these annoying. Is there a way to set a specific time when notifications happen, so I can choose a time within our working hours?

**Comment by dblock** [comment]
I rolled out a change made in https://github.com/dblock/slack-sup2/commit/bd36978e8fbaa4022a4f0613bf19b6fbcf00d6c8 which sends reminders only after S'Up time of day. 

Note that `Thanks, I'll ask again in a couple of days.` is a result of someone clicking the button that says "We haven't met yet.", so it's not on a timer.

LMK how this works out!

**Comment by dblock** [comment]
Applied same in S'Up v1, https://github.com/dblock/slack-sup/commit/007c504a21649d22eb82e68b966bd1219711b9f7.
